version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - DJNGO_SECRET_KEY=${DJNGO_SECRET_KEY}
      - POSTGRE_DB=${POSTGRE_DB}
      - POSTGRE_USER=${POSTGRE_USER}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRE_HOST=postgres
      - POSTGRE_PORT=${POSTGRE_PORT}
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRE_DB}
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
