# Generated by Django 5.1.4 on 2024-12-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_users', to='room.chatroommodel', verbose_name='Chat Room')),
            ],
            options={
                'verbose_name': 'Connected User',
                'verbose_name_plural': 'Connected Users',
                'db_table': 'apps_connected_user',
            },
        ),
    ]
